// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetMessagesByContact(arg1) {
  return window['go']['main']['App']['GetMessagesByContact'](arg1);
}

export function SaveMessage(arg1, arg2) {
  return window['go']['main']['App']['SaveMessage'](arg1, arg2);
}
