// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContacts():Promise<Array<Record<string, string>>>;

export function GetMessagesByContact(arg1:string):Promise<Array<Record<string, string>>>;

export function SaveMessage(arg1:string,arg2:string):Promise<string>;
